
name: test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'branch name or version tag or commit hash: main / v0.0.1 / acdefg'
        default: 'main'
        required: true
        type: string
      python_version:
        description: 'python_version: multiple versions separated by ,'
        default: '3.10'
        required: true
        type: string
      torch_version:
        description: 'torch_version: multiple versions separated by ,'
        default: '2.1.2,2.4.0'
        required: true
        type: string
      cuda_version:
        description: 'cuda_version: multiple versions separated by ,'
        default: '11.8.0,12.1.0'
        required: true
        type: string

jobs:
  set_ver:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.parse_versions.outputs.matrix }}
    steps:
      - name: Parse versions
        id: parse_versions
        run: |
          echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
          echo "${matrix}"

  wheel:
    name: ${{ matrix.project }}
    needs: set_ver
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}

    steps:
      - name: Debug matrix
        run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"
